# Author: blss-tico (github.com/blss-tico)

# nginx reverse proxy container
FROM nginx:1.25.1-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
